<html>
	<body>
		<h1>WEBAPPS</h1>
		<div>
			<a href="https://www.instagram.com"><img src ="<?=IMGURL?>instagram.png" /></a>
            <p>instagram</p>
        </div>
        <div>
            <a href="https://www.google.com/maps?force=tt&source=ttpwa"><img src ="<?=IMGURL?>googlemaps.png" /></a>
            <p>Google Maps</p>
        </div>
        <div>
            <a href="https://web.whatsapp.com">WhatsApp</a>
        </div>
        <div>
            <a href-="http://web.skype.com ">SKYPE</a>
        </div>
        <div>
            <a href="https://mobile.twitter.com"><img src ="<?=IMGURL?>twitter.png" /></a>
            <p>Twitter</p>
        </div>
	</body>	
</html>